#ifndef BASELINER_REGISTER_HPP
#define BASELINER_REGISTER_HPP

#define BASELINER_REGISTER_STAT(Stat)

#define BASELINER_REGISTER_STOPPING_CRITERION(Stopping)

#define BASELINER_REGISTER_DEFAULT_STATS(DefaultStats)

#define BASELINER_REGISTER_BENCHMARK(Benchmark)

#define BASELINER_REGISTER_BACKEND(name, Backend)

#define BASELINER_REGISTER_BACKEND_STATS(Stat)

#if defined(ADAPTER_BACKEND_NVBENCH)
#include <adapters/NVBenchRegister.hpp>

#define BASELINER_REGISTER_WORKLOAD(Workload) NVBENCH_REGISTER_WORKLOAD(Workload)

#define BASELINER_REGISTER_WORKLOAD_NAME(Workload, name) NVBENCH_REGISTER_WORKLOAD_NAME(Workload, name)

#define BASELINER_REGISTER_KERNEL(Kernel) NVBENCH_REGISTER_KERNEL(Workload, name)

#elif defined(ADAPTER_BACKEND_PRIMBENCH)
#include <adapters/PrimBenchRegister.hpp>

#define BASELINER_REGISTER_WORKLOAD(Workload) PRIMBENCH_REGISTER_WORKLOAD(Workload)

#define BASELINER_REGISTER_WORKLOAD_NAME(Workload, name) PRIMBENCH_REGISTER_WORKLOAD_NAME(Workload, name)

#define BASELINER_REGISTER_KERNEL(Kernel) PRIMBENCH_REGISTER_KERNEL(Workload, name)

#endif

#endif // BASELINER_REGISTRY_REGISTERINGMACROS_HPP